---
version: '3'

services:
  mdbook:
    container_name: mdbook
    image: ghcr.io/xavier2p/mdbook:latest
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'