site_name: The /forge Wiki
docs_dir: src/

repo_name: the-forge-lab
repo_url: https://github.com/the-forge-lab

copyright: 2023 &copy; Xavier2p

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - navigation.footer
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  font: false
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: material/github

plugins:
  - search

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/Xavier2p
    - name: Discord
      icon: fontawesome/brands/discord
      link: https://discord.gg/DTYaBjdSC

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Services:
    - Media:
      - media/index.md
      - Jellyfin: media/jellyfin.md
      - Jellyseerr: media/jellyseerr.md
      - MeTube: media/metube.md
    - Cloud:
      - cloud/index.md
      - Nextcloud: cloud/nextcloud.md
      - OnlyOffice: cloud/onlyoffice.md
      - PhotoPrism: cloud/photoprism.md
    - Other:
      - others/index.md
      - FreshRSS: others/freshrss.md
      - Homer: others/homer.md
      - Libreddit: others/libreddit.md
      - Mealie: others/mealie.md
      - Speedtest: others/speedtest.md
      - Uptime Kuma: others/uptime-kuma.md
  - Infrastructure:
    - infra/index.md
    - Hosts:
      - infra/hosts/index.md
      - Scariff: infra/hosts/scariff.md
      - Mandalore: infra/hosts/mandalore.md
      - Exegol: infra/hosts/exegol.md
      - Nevarro: infra/hosts/nevarro.md
      - Moraband: infra/hosts/moraband.md
    - System: infra/system.md
    - As Code: infra/as-code.md
  - Deployment:
    - deployment/index.md
    - Requirements: deployment/requirements.md
    - Ansible: deployment/pre-deployment.md
    - Deploy: deployment/deploy.md
  - About:
    - about/index.md
    - Contributing: about/contributing.md
    - Credits: about/credits.md
    - License: about/license.md
